Cyber/urls.py
from django.contrib import admin
from django.urls import path , include


# upload
from django.conf import settings
from django.conf.urls.static import static
from FaceDetection import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('log/' ,include('login.urls')),
    path('reg/' ,include('register.urls')),
    path('logo/' , include('logout.urls')),
    path('dash/', include('dashboard.urls')),
    path("face/" , include("FaceDetection.urls")),
    


    
] + static(settings.MEDIA_URL  , document_root = settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('files/', views.files, name='files'),
    path('notifications/', views.notifications, name='notifications'),
    path('chart/', views.chart, name='chart'),
    # path('facial/', views.facial, name= 'facialdetection'),
    path('passport/', views.passport, name='passport'),
    path('vehicle/', views.vehicle, name='vehicle'),
    path('license/', views.license, name = 'license'),
    path('cdr/', views.cdr, name='cdr'),
    path('interrogation/', views.interrogation, name='interrogation'),    
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/' , views.login_page, name= 'login_page'),
    
]

register/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('files/', views.files, name='files'),
    path('notifications/', views.notifications, name='notifications'),
    path('chart/', views.chart, name='chart'),
    path('facial/', views.facial, name= 'facialdetection'),
    path('passport/', views.passport, name='passport'),
    path('vehicle/', views.vehicle, name='vehicle'),
    path('license/', views.license, name = 'license'),
    path('cdr/', views.cdr, name='cdr'),
    path('interrogation/', views.interrogation, name='interrogation'),    
]

register/dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
# views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

def files(request):
    return render(request, 'dashboard/files.html')

def notifications(request):
    return render(request, 'dashboard/notifications.html')

def chart(request):
    return render(request, 'dashboard/chart.html')

# def facial(request):
#     return render(request, 'dashboard/facialdetection.html')

def passport(request):
    return render(request, 'dashboard/passport.html')

def vehicle(request):
    return render(request, 'dashboard/vehicle.html')

def license(request):
    return render(request, 'dashboard/license.html')

def cdr(request):
    return render(request, 'dashboard/cdr.html')

def interrogation(request):
    return render(request, 'dashboard/interrogation.html')

register/dashboard/views.py
# views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

def files(request):
    return render(request, 'dashboard/files.html')

def notifications(request):
    return render(request, 'dashboard/notifications.html')

def chart(request):
    return render(request, 'dashboard/chart.html')

def facial(request):
    return render(request, 'dashboard/facialdetection.html')

def passport(request):
    return render(request, 'dashboard/passport.html')

def vehicle(request):
    return render(request, 'dashboard/vehicle.html')

def license(request):
    return render(request, 'dashboard/license.html')

def cdr(request):
    return render(request, 'dashboard/cdr.html')

def interrogation(request):
    return render(request, 'dashboard/interrogation.html')

register/dashboard/templates/dashboard/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>

    

    <link rel="stylesheet" href="{% static 'dashboard/css/base.css' %}">
    

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
</head>

<body>
    <nav>
        <label class="logo">
            <img
                src="https://imgs.search.brave.com/Op63nSQg9Za6Z1qfRK0vFg-Zu65vials2D0SkPjZ7iw/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9tYXBs/ZWNsb3VkLmNvbS5h/dS93cC1jb250ZW50/L3VwbG9hZHMvMjAy/MS8wMy9NYXBsZS1D/bG91ZC1Mb2dvLTIt/Mi5wbmc">
        </label>
        <ul>
            <li><a class="active" href="{% url 'dashboard' %}">Home</a></li>
            <li>
                <a href="{% url 'files' %}">Files
                    <i class="fas fa-caret-down"></i>
                </a>
                <ul>
                    <li><a href="#">Python</a></li>
                    <li><a href="#">JQuery</a></li>
                    <li><a href="#">Javascript</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Detection
                    <i class="fas fa-caret-down"></i>
                </a>
                <ul>
                    <li><a href="{% url 'facialdetection' %}">Facial Detection</a></li>

                    <li>
                        <a href="#">Document Detection
                            <i class="fas fa-caret-right"></i>
                        </a>
                        <ul>
                            <li><a href="{% url 'passport' %}">Passport Data</a></li>
                            <li><a href="{% url 'vehicle' %}">Vehicle Registration Data</a></li>
                            <li><a href="{% url 'license' %}">License Card Holder Data</a></li>
                            <li><a href="{% url 'cdr' %}">CDR's</a></li>
                            <li><a href="{%url 'interrogation' %}">Interrogation Reports</a></li>
                            <li><a href="#">Intelligence Inputs</a></li>
                            <li><a href="#">FIR's</a></li>
                            <li><a href="#">Travel Related Info</a></li>
                            <li><a href="#">Crime Related Info</a></li>
                            <li><a href="#">Others</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="{% url 'chart' %}">Charts</a></li>
            <li><a href="{% url 'notifications' %}">Notifications</a></li>

            <li><a href="{% url 'login:login' %}">Logout</a></li>
        </ul>
    </nav>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

register/dashboard/templates/dashboard/cdr.html
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Add notifications content here -->

<h1>Call Detail Records</h1>

<div class="files">
    <h3>Uplaod File: </h3>
    <input type="file" name="Upload File" id="file">
</div>

<div class="submit">
    <input type="submit" value="Submit">
</div>

{% endblock %}

register/dashboard/templates/dashboard/chart.html
<!-- templates/notifications.html -->
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}

<!-- Add chart content here -->

<h1>Charts</h1>

<div class="div1">
    <div id="barchart_values"></div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", { packages: ["corechart"] });
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ["Element", "Density", { role: "style" }],
                ["Copper", 8.94, "#b87333"],
                ["Silver", 10.49, "silver"],
                ["Gold", 19.30, "gold"],
                ["Platinum", 21.45, "color: #e5e4e2"]
            ]);

            var view = new google.visualization.DataView(data);
            view.setColumns([0, 1,
                {
                    calc: "stringify",
                    sourceColumn: 1,
                    type: "string",
                    role: "annotation"
                },
                2]);

            var options = {
                title: "Density of Precious Metals, in g/cm^3",
                width: 600,
                height: 400,
                bar: { groupWidth: "95%" },
                legend: { position: "none" },
            };
            var chart = new google.visualization.BarChart(document.getElementById("barchart_values"));
            chart.draw(view, options);
        }
    </script>


    <div id="piechart_3d"></div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", { packages: ["corechart"] });
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Task', 'Hours per Day'],
                ['Work', 11],
                ['Eat', 2],
                ['Commute', 2],
                ['Watch TV', 2],
                ['Sleep', 7]
            ]);

            var options = {
                title: 'My Daily Activities',
                is3D: true,
            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
            chart.draw(data, options);
        }
    </script>
</div>


<div class="div2">
   <div id="chart_div1" ></div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { packages: ['corechart', 'bar'] });
        google.charts.setOnLoadCallback(drawColColors);

        function drawColColors() {
            var data = new google.visualization.DataTable();
            data.addColumn('timeofday', 'Time of Day');
            data.addColumn('number', 'Motivation Level');
            data.addColumn('number', 'Energy Level');

            data.addRows([
                [{ v: [8, 0, 0], f: '8 am' }, 1, .25],
                [{ v: [9, 0, 0], f: '9 am' }, 2, .5],
                [{ v: [10, 0, 0], f: '10 am' }, 3, 1],
                [{ v: [11, 0, 0], f: '11 am' }, 4, 2.25],
                [{ v: [12, 0, 0], f: '12 pm' }, 5, 2.25],
                [{ v: [13, 0, 0], f: '1 pm' }, 6, 3],
                [{ v: [14, 0, 0], f: '2 pm' }, 7, 4],
                [{ v: [15, 0, 0], f: '3 pm' }, 8, 5.25],
                [{ v: [16, 0, 0], f: '4 pm' }, 9, 7.5],
                [{ v: [17, 0, 0], f: '5 pm' }, 10, 10],
            ]);

            var options = {
                title: 'Motivation and Energy Level Throughout the Day',
                colors: ['#9575cd', '#33ac71'],
                hAxis: {
                    title: 'Time of Day',
                    format: 'h:mm a',
                    viewWindow: {
                        min: [7, 30, 0],
                        max: [17, 30, 0]
                    }
                },
                vAxis: {
                    title: 'Rating (scale of 1-10)'
                }
            };

            var chart = new google.visualization.ColumnChart(document.getElementById('chart_div1'));
            chart.draw(data, options);
        }    </script>

    
    <div id="chart_div"></div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { packages: ['corechart', 'line'] });
        google.charts.setOnLoadCallback(drawBasic);

        function drawBasic() {

            var data = new google.visualization.DataTable();
            data.addColumn('number', 'X');
            data.addColumn('number', 'Dogs');

            data.addRows([
                [0, 0], [1, 10], [2, 23], [3, 17], [4, 18], [5, 9],
                [6, 11], [7, 27], [8, 33], [9, 40], [10, 32], [11, 35],
                [12, 30], [13, 40], [14, 42], [15, 47], [16, 44], [17, 48],
                [18, 52], [19, 54], [20, 42], [21, 55], [22, 56], [23, 57],
                [24, 60], [25, 50], [26, 52], [27, 51], [28, 49], [29, 53],
                [30, 55], [31, 60], [32, 61], [33, 59], [34, 62], [35, 65],
                [36, 62], [37, 58], [38, 55], [39, 61], [40, 64], [41, 65],
                [42, 63], [43, 66], [44, 67], [45, 69], [46, 69], [47, 70],
                [48, 72], [49, 68], [50, 66], [51, 65], [52, 67], [53, 70],
                [54, 71], [55, 72], [56, 73], [57, 75], [58, 70], [59, 68],
                [60, 64], [61, 60], [62, 65], [63, 67], [64, 68], [65, 69],
                [66, 70], [67, 72], [68, 75], [69, 80]
            ]);

            var options = {
                hAxis: {
                    title: 'Time'
                },
                vAxis: {
                    title: 'Popularity'
                }
            };

            var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

            chart.draw(data, options);
        }
    </script>
</div>

{% endblock %}
<script src="{% static 'dashboard/js/script.js' %}"></script>

register/dashboard/templates/dashboard/dashboard.html
<!-- templates/dashboard.html -->
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}

<!-- Add dashboard content here -->

<div class="image">
    <h1>Dashboard</h1>

</div>

{% endblock %}

register/dashboard/templates/dashboard/facialdetection.html
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Add notifications content here -->

<h1>Facial Detection</h1>

<h3>Uplaod Photos To Detect Enimy</h3>
<input type="file" name="Upload image" id="image">






{% endblock %}

register/dashboard/templates/dashboard/files.html
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Add notifications content here -->

<h1> Uplaod Files</h1>
<form>
    <div class="type">
        <h3> <label for="type">Choose a file Type:</label> </h3>
        <select name="type" id="type">
            <option value="select">Select Type</option>
            <option value="excel">Excel</option>
            <option value="pdf">PDF</option>
            <option value="image">Image</option>
            <option value="video">Video</option>
            <option value="word">Word</option>
        </select>
    </div>
    
    <div class="files">
        <h3>Uplaod File</h3>
        <input type="file" name="Upload File" id="file">
    </div>

    <div class="submit">
        <input type="submit" value="Submit">
    </div>
</form>


{% endblock %}

register/dashboard/templates/dashboard/interrogation.html
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Add notifications content here -->

<h1>Interrogation Reports</h1>

<div class="text">
    <form>
        <label for="InterrogationID">Interrogation Id: </label>
        <input type="text" id="IntID" name="InterrogationID" placeholder="Interrogation ID">
</div>

<div class="submit">
    <input type="submit" value="Submit">
</div>

{% endblock %}

register/dashboard/templates/dashboard/license.html
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Add notifications content here -->

<h1>License Card Holder Data</h1>

<div class="text">
    <form>
        <label for="license">License Number: </label>
        <input type="text" id="license ID" name="licenseID" placeholder="License Number">
</div>

<div class="submit">
    <input type="submit" value="Submit">
</div>

{% endblock %}

register/dashboard/templates/dashboard/notifications.html
<!-- templates/notifications.html -->
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Add notifications content here -->



<h1>Notifications</h1>


{% endblock %}

register/dashboard/templates/dashboard/passport.html
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Add notifications content here -->

<h1>Passport Data</h1>


<div class="text">
    <form>
        <label for="passID">Passport Number: </label>
        <input type="text" id="PassID" name="Passportnumber" placeholder="passport ID">
</div>

<div class="submit">
    <input type="submit" value="Submit">
</div>

{% endblock %}

register/dashboard/templates/dashboard/vehicle.html
{% extends 'dashboard/base.html' %}
{% block content %}

<!-- Add notifications content here -->

<h1>Vehichle Registration Data</h1>

<div class="text">
    <form>
        <label for="vehicle">Vehichle Number: </label>
        <input type="text" id="license ID" name="vehicleno" placeholder="Vehicle Number">
</div>

<div class="submit">
    <input type="submit" value="Submit">
</div>

{% endblock %}