Cyber/urls.py
from django.contrib import admin
from django.urls import path , include


# upload
from django.conf import settings
from django.conf.urls.static import static
from FaceDetection import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('log/' ,include('login.urls')),
    path('reg/' ,include('register.urls')),
    path('logo/' , include('logout.urls')),
    path('dash/', include('dashboard.urls')),
    path("face/" , include("FaceDetection.urls")),
    


    
] + static(settings.MEDIA_URL  , document_root = settings.MEDIA_ROOT)

FaceDetection/urls.py
from django.urls import path 

from . import views
app_name = 'FaceDetection'

urlpatterns = [
    path("facedetection/" , views.show , name='facedetection'),
    path("FaceDetectionVedio/" , views.video_show , name='FaceDetectionVedio'),
    # Another Tab Inside Show the Video
    # path("videoshow/" , views.video_show , name = 'videoshow'),
    path("videoshow/" , views.video_show , name= "videoshow"),
    path("video_show/" , views.videoshow , name= "video_show"),






]

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('files/', views.files, name='files'),
    path('notifications/', views.notifications, name='notifications'),
    path('chart/', views.chart, name='chart'),
    # path('facial/', views.facial, name= 'facialdetection'),
    path('passport/', views.passport, name='passport'),
    path('vehicle/', views.vehicle, name='vehicle'),
    path('license/', views.license, name = 'license'),
    path('cdr/', views.cdr, name='cdr'),
    path('interrogation/', views.interrogation, name='interrogation'),    
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/' , views.login_page, name= 'login_page'),
    
]

register/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('files/', views.files, name='files'),
    path('notifications/', views.notifications, name='notifications'),
    path('chart/', views.chart, name='chart'),
    path('facial/', views.facial, name= 'facialdetection'),
    path('passport/', views.passport, name='passport'),
    path('vehicle/', views.vehicle, name='vehicle'),
    path('license/', views.license, name = 'license'),
    path('cdr/', views.cdr, name='cdr'),
    path('interrogation/', views.interrogation, name='interrogation'),    
]

register/dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
# views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

def files(request):
    return render(request, 'dashboard/files.html')

def notifications(request):
    return render(request, 'dashboard/notifications.html')

def chart(request):
    return render(request, 'dashboard/chart.html')

# def facial(request):
#     return render(request, 'dashboard/facialdetection.html')

def passport(request):
    return render(request, 'dashboard/passport.html')

def vehicle(request):
    return render(request, 'dashboard/vehicle.html')

def license(request):
    return render(request, 'dashboard/license.html')

def cdr(request):
    return render(request, 'dashboard/cdr.html')

def interrogation(request):
    return render(request, 'dashboard/interrogation.html')

register/dashboard/views.py
# views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

def files(request):
    return render(request, 'dashboard/files.html')

def notifications(request):
    return render(request, 'dashboard/notifications.html')

def chart(request):
    return render(request, 'dashboard/chart.html')

def facial(request):
    return render(request, 'dashboard/facialdetection.html')

def passport(request):
    return render(request, 'dashboard/passport.html')

def vehicle(request):
    return render(request, 'dashboard/vehicle.html')

def license(request):
    return render(request, 'dashboard/license.html')

def cdr(request):
    return render(request, 'dashboard/cdr.html')

def interrogation(request):
    return render(request, 'dashboard/interrogation.html')

dashboard/templates/dashboard/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'dashboard/images/favicon.png' %}"
    />
    <link rel="stylesheet" href="{% static 'dashboard/css/base.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
  </head>
  <body>
    <div class="navbar">
    <nav>
      <label class="logo" id="img_logo">
        <img src="{% static 'dashboard/images/logo2.png' %}" alt="Logo" />
      </label>
      <div class="icon">
        <ul>
          <li><a class="active" href="{% url 'dashboard:dashboard' %}">Home</a></li>
          <li>
            <a href="{% url 'dashboard:files' %}"
              >Files
              <i class="fas fa-caret-down"></i>
            </a>
            <ul>
              <li><a href="#">Python</a></li>
              <li><a href="#">JQuery</a></li>
              <li><a href="#">Javascript</a></li>
            </ul>
          </li>
          <li>
            <a href="#"
              >Detection
              <i class="fas fa-caret-down"></i>
            </a>
            <ul>
              <li>
                <a href="#"
                  >Face Detection
                  <i class="fas fa-caret-right"></i>
                </a>
                <ul>
                  <li>
                    <a href="{% url 'FaceDetection:facedetection' %}"
                      >Image Detect</a
                    >
                  </li>
                  <li>
                    <a href="{% url 'FaceDetection:FaceDetectionVedio' %}">Video Detect</a>
                  </li>
                </ul>
              </li>
              <li>
                <a href="#"
                  >Document Detection
                  <i class="fas fa-caret-right"></i>
                </a>
                <ul>
                  <li><a href="{% url 'dashboard:passport' %}">Passport Data</a></li>
                  <li>
                    <a href="{% url 'dashboard:vehicle' %}">Vehicle Registration Data</a>
                  </li>
                  <li>
                    <a href="{% url 'dashboard:license' %}">License Card Holder Data</a>
                  </li>
                  <li><a href="{% url 'dashboard:cdr' %}">CDR's</a></li>
                  <li>
                    <a href="{%url 'dashboard:interrogation' %}">Interrogation Reports</a>
                  </li>
                  <li><a href="#">Intelligence Inputs</a></li>
                  <li><a href="#">FIR's</a></li>
                  <li><a href="#">Travel Related Info</a></li>
                  <li><a href="#">Crime Related Info</a></li>
                  <li><a href="#">Others</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li><a href="{% url 'dashboard:chart' %}">Charts</a></li>
          <li><a href="{% url 'dashboard:notifications' %}">Notifications</a></li>
          <li><a href="{% url 'login:login_page' %}">Logout</a></li>
        </ul>
      </div>
    </nav>
  </div>
    <div class="content">{% block content %}
      {% endblock %}</div>
  </body>
</html>

dashboard/templates/dashboard/dashboard.html
<!-- templates/dashboard.html -->
{% extends 'dashboard/base.html' %} {% load static %} {% block content %}
<!-- Add dashboard content here -->
<div class="image">
  <div class="buttons">
    <div class="recognition link-btn">
        <i class="bi bi-person-bounding-box"></i>
      <a href="{% url 'FaceDetection:facedetection' %}" class="button">Recognition</a>
    </div>
    <div class="trust link-btn">
        <i class="bi bi-shield-check"></i>
      <a href="#" class="button">Trust Guard</a>
    </div>
    <div class="eye link-btn">
        <i class="bi bi-eye"></i>
      <a href="#" class="button">Eye Scanner</a>
    </div>
  </div>
</div>
{% endblock %}

dashboard/templates/dashboard/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello </h1>
</body>
</html>